### ISSUE TITLE
how to make input type=file look better

### ISSUE THREAD

**Issue by 4agoodcause** [4agoodcause/dashboard#7]
Was not able to find a good way to format the form element on the Image Upload page. Take  alook and let me know what you think. 

Thanks.

**Comment by bradsawicki** [comment]
I noticed you pushed to the repo! That's awesome! I'm using SASS as the CSS preprocessor, so I can't push to master anymore or I'd have to overwrite your application.css file, but I created a new branch "feedback_updates" and will push to that for reference. Continue to use master and I'll use the new branch.

As for the file input, there isn't much we can do with them, unfortunately. Webkit browsers are the only ones that have some flexibility with styling file inputs. Remove the input[type="file"] from the button styles and instead, add the following to your main stylesheet:

https://github.com/4agoodcause/dashboard/blob/feedback_updates/assets/css/application.css#L466-L480

**Comment by 4agoodcause** [comment]
Will do. This will work.
